exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('movies').del()
    .then(function () {
      // Inserts seed entries
      return knex('movies').insert([
        { id: 1, name: 'Joker (I) (2019)', image: '/images/1.png' },
        { id: 2, name: 'Iron Man (2008)', image: '/images/2.png' },
        { id: 3, name: 'The Incredible Hulk (2008)', image: '/images/3.png' },
        { id: 4, name: 'Iron Man 2 (2010)', image: '/images/4.png' },
        { id: 5, name: 'Thor (2011)', image: '/images/5.png' },
        { id: 6, name: 'Captain America: The First Avenger (2011)', image: '/images/6.png' },
        { id: 7, name: 'Marvels The Avengers (2019)', image: '/images/7.png' },
        { id: 8, name: ' The Godfather: Part II  (1974)', image: '/images/8.png' },
        { id: 9, name: 'The Lives of Others  (2006)', image: '/images/9.png' },
        { id: 10, name: ' Avengers: Infinity War (2018)', image: '/images/10.png' },
        { id: 11, name: 'The Dark Knight Rises (2012)', image: '/images/11.png' },
        { id: 12, name: 'Your Name. (2016)', image: '/images/12.png' },
        { id: 13, name: 'Coco (2017)', image: '/images/13.png' },
        { id: 14, name: '3 Idiots (2009)', image: '/images/14.png' },
        { id: 15, name: 'Like Stars on Earth (2007)', image: '/images/15.png' },
        { id: 16, name: 'Toy Story (1995)', image: '/images/16.png' },
        { id: 17, name: 'The Kid (1921)', image: '/images/17.png' },
        { id: 18, name: 'The Chaos Class (1975)', image: '/images/18.png' },
        { id: 19, name: 'Life Is Beautiful (1997)', image: '/images/19.png' },
        { id: 20, name: 'The Intouchables (2011)', image: '/images/20.png' },
        { id: 21, name: 'Back to the Future (1985)', image: '/images/21.png' },
        { id: 22, name: 'Modern Times (1936)', image: '/images/22.png' },
        { id: 23, name: 'Snatch (2000)', image: '/images/23.png' },
        { id: 24, name: 'Star Wars: Episode V - The Empire Strikes Back (1980)', image: '/images/24.png' },
        { id: 25, name: 'The Green Mile (1999)', image: '/images/25.png' },
        { id: 26, name: '12 Years a Slave (2013)', image: '/images/26.png' },
        { id: 27, name: 'Airlift (2016)', image: '/images/27.png' },
        { id: 28, name: 'Let the Right One In (2008)', image: '/images/28.png' },
        { id: 29, name: 'Night of the Living Dead (1968)', image: '/images/29.png' },
        { id: 30, name: 'I Saw the Devil (2010)', image: '/images/30.png' },
        { id: 31, name: 'Spirited Away (2001)', image: '/images/31.png' },
        { id: 32, name: 'The Prestige (2006)', image: '/images/32.png' },
        { id: 33, name: 'Bone Tomahawk (2015)', image: '/images/33.png' },
        { id: 34, name: 'The Lion King (2019)', image: '/images/34.png' },
        { id: 35, name: 'The Irishman (2019)', image: '/images/35.png' },
        { id: 36, name: 'Knives Out (2019)', image: '/images/36.png' },
        { id: 37, name: 'Marriage Story (2019)', image: '/images/37.png' },
        { id: 38, name: 'Little Women (2019)', image: '/images/38.png' },
        { id: 39, name: 'Green Book (2018)', image: '/images/39.png' },
        { id: 40, name: 'Logan (2017)', image: '/images/40.png' },
        { id: 41, name: 'Hacksaw Ridge (2016)', image: '/images/41.png' },
        { id: 42, name: 'Room (2015)', image: '/images/42.png' },
        { id: 43, name: 'A Quiet Place (2018)', image: '/images/43.png' },
        { id: 44, name: 'Parasite (2019)', image: '/images/44.png' },
        { id: 45, name: 'Doctor Sleep (2019)', image: '/images/45.png' },
        { id: 46, name: 'Rambo: Last Blood (2019)', image: '/images/46.png' },
        { id: 47, name: 'Midsommar (2019)', image: '/images/47.png' },
        { id: 48, name: 'Dark Waters (2019)', image: '/images/48.png' },
        { id: 49, name: 'Dunkirk (2017)', image: '/images/49.png' },
        { id: 50, name: '13 Hours (2016)', image: '/images/50.png' },
        { id: 51, name: 'Never Look Away (2018)', image: '/images/51.png' },
        { id: 52, name: 'The Impossible (2012)', image: '/images/52.png' },
        { id: 53, name: 'Gone Girl (2014)', image: '/images/53.png' },
        { id: 54, name: 'Guardians of the Galaxy (2014)', image: '/images/54.png' },
        { id: 55, name: 'Whiplash (2014)', image: '/images/55.png' },
        { id: 56, name: 'The Wolf of Wall Street (2013)', image: '/images/56.png' },
        { id: 57, name: 'Rush (2013)', image: '/images/57.png' },
        { id: 58, name: 'Prisoners (2013)', image: '/images/58.png' },
        { id: 59, name: 'Inception (2010)', image: '/images/59.png' },
        { id: 60, name: 'How to Train Your Dragon (2010)', image: '/images/60.png' },
        { id: 61, name: '3 Idiots (2009)', image: '/images/61.png' },
        { id: 62, name: 'The Secret in Their Eyes (2009)', image: '/images/62.png' },
        { id: 63, name: 'The Dark Knight (2008)', image: '/images/63.png' },
        { id: 64, name: 'Million Dollar Baby (2004)', image: '/images/64.png' },
        { id: 65, name: 'Downfall (2004)', image: '/images/65.png' },
        { id: 66, name: 'Before Sunset (2004)', image: '/images/66.png' }
      ])
    })
}
