exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('movies_genres').del()
    .then(function () {
      // Inserts seed entries
      return knex('movies_genres').insert([
        { id: 1, movie_id: 1, genre_id: 6 },
        { id: 2, movie_id: 1, genre_id: 7 },
        { id: 3, movie_id: 1, genre_id: 19 },
        { id: 4, movie_id: 2, genre_id: 1 },
        { id: 5, movie_id: 2, genre_id: 2 },
        { id: 6, movie_id: 2, genre_id: 17 },
        { id: 7, movie_id: 3, genre_id: 1 },
        { id: 8, movie_id: 3, genre_id: 2 },
        { id: 9, movie_id: 3, genre_id: 17 },
        { id: 10, movie_id: 4, genre_id: 1 },
        { id: 11, movie_id: 4, genre_id: 2 },
        { id: 12, movie_id: 4, genre_id: 17 },
        { id: 13, movie_id: 5, genre_id: 1 },
        { id: 14, movie_id: 5, genre_id: 2 },
        { id: 15, movie_id: 5, genre_id: 9 },
        { id: 16, movie_id: 6, genre_id: 1 },
        { id: 17, movie_id: 6, genre_id: 2 },
        { id: 18, movie_id: 6, genre_id: 17 },
        { id: 19, movie_id: 7, genre_id: 1 },
        { id: 20, movie_id: 7, genre_id: 2 },
        { id: 21, movie_id: 7, genre_id: 17 },
        { id: 22, movie_id: 8, genre_id: 6 },
        { id: 23, movie_id: 8, genre_id: 7 },
        { id: 24, movie_id: 9, genre_id: 7 },
        { id: 25, movie_id: 9, genre_id: 19 },
        { id: 26, movie_id: 10, genre_id: 1 },
        { id: 27, movie_id: 10, genre_id: 2 },
        { id: 28, movie_id: 10, genre_id: 17 },
        { id: 29, movie_id: 11, genre_id: 1 },
        { id: 30, movie_id: 11, genre_id: 19 },
        { id: 31, movie_id: 12, genre_id: 3 },
        { id: 32, movie_id: 12, genre_id: 7 },
        { id: 33, movie_id: 12, genre_id: 9 },
        { id: 34, movie_id: 13, genre_id: 2 },
        { id: 35, movie_id: 13, genre_id: 3 },
        { id: 36, movie_id: 13, genre_id: 8 },
        { id: 37, movie_id: 14, genre_id: 5 },
        { id: 38, movie_id: 14, genre_id: 7 },
        { id: 39, movie_id: 15, genre_id: 7 },
        { id: 40, movie_id: 15, genre_id: 8 },
        { id: 41, movie_id: 16, genre_id: 2 },
        { id: 42, movie_id: 16, genre_id: 3 },
        { id: 43, movie_id: 16, genre_id: 5 },
        { id: 44, movie_id: 17, genre_id: 5 },
        { id: 45, movie_id: 17, genre_id: 7 },
        { id: 46, movie_id: 17, genre_id: 8 },
        { id: 47, movie_id: 18, genre_id: 5 },
        { id: 48, movie_id: 18, genre_id: 7 },
        { id: 49, movie_id: 19, genre_id: 5 },
        { id: 50, movie_id: 19, genre_id: 7 },
        { id: 51, movie_id: 19, genre_id: 16 },
        { id: 52, movie_id: 20, genre_id: 4 },
        { id: 53, movie_id: 20, genre_id: 5 },
        { id: 54, movie_id: 20, genre_id: 7 },
        { id: 55, movie_id: 21, genre_id: 2 },
        { id: 56, movie_id: 21, genre_id: 5 },
        { id: 57, movie_id: 21, genre_id: 17 },
        { id: 58, movie_id: 22, genre_id: 5 },
        { id: 59, movie_id: 22, genre_id: 7 },
        { id: 60, movie_id: 22, genre_id: 8 },
        { id: 61, movie_id: 23, genre_id: 5 },
        { id: 62, movie_id: 23, genre_id: 6 },
        { id: 63, movie_id: 24, genre_id: 1 },
        { id: 64, movie_id: 24, genre_id: 2 },
        { id: 65, movie_id: 24, genre_id: 9 },
        { id: 66, movie_id: 25, genre_id: 6 },
        { id: 67, movie_id: 25, genre_id: 7 },
        { id: 68, movie_id: 25, genre_id: 9 },
        { id: 69, movie_id: 26, genre_id: 4 },
        { id: 70, movie_id: 26, genre_id: 7 },
        { id: 71, movie_id: 26, genre_id: 11 },
        { id: 72, movie_id: 27, genre_id: 7 },
        { id: 73, movie_id: 27, genre_id: 11 },
        { id: 74, movie_id: 28, genre_id: 7 },
        { id: 75, movie_id: 28, genre_id: 12 },
        { id: 76, movie_id: 28, genre_id: 16 },
        { id: 77, movie_id: 29, genre_id: 12 },
        { id: 78, movie_id: 30, genre_id: 1 },
        { id: 79, movie_id: 30, genre_id: 6 },
        { id: 80, movie_id: 30, genre_id: 7 },
        { id: 81, movie_id: 31, genre_id: 2 },
        { id: 82, movie_id: 31, genre_id: 3 },
        { id: 83, movie_id: 31, genre_id: 8 },
        { id: 84, movie_id: 32, genre_id: 7 },
        { id: 85, movie_id: 32, genre_id: 15 },
        { id: 86, movie_id: 32, genre_id: 17 }
      ])
    })
}
