name: Test and Deploy

on: 
  push:
    branches:
      - master
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      run: |
        yarn
        yarn test
    - name: build
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        APP_NAME: ${{ 'moviesrecommend' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME   

